import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/themes/catppuccin-mocha.toml"
  "~/.config/alacritty/themes/rose-pine.toml"
]

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = false
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 6
y = 6
